name: Artifacts
on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: echo "Hello, This is Ned Stark⚔️" > output.txt
      - uses: actions/upload-artifact@v6.0.0
        with:
          name: output-artifact
          path: output.txt

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:  
      - name: Download Artifacts
        uses: actions/download-artifact@v7.0.0
        with:
          name: output-artifact
          path: output
