name: Environment Variables
on: push
env:
  GLOBAL_ENV: "I'm WF Env"
jobs:
  Build:
    env:
      JOB_ENV: "I'm Job Env"
    runs-on: ubuntu-latest
    steps:
      - name: Env Print
        env:
          STEP_ENV: "I'm Step Env"
        run: |
          echo "Global env -> ${{env.GLOBAL_ENV}}"
          echo "Job env -> ${{env.JOB_ENV}}"
          echo "Step env -> ${{env.STEP_ENV}}"
          echo "VERSION=1.0.0" >> $GITHUB_ENV

      - name: Dynamic env
        run: echo $VERSION

      - name: Default env
        run: echo $GITHUB_REPOSITORY

      - name: Secret env
        run: echo ${{secrets.NAME}}

      
