name: Execute Py Script
on:
  workflow_dispatch:

jobs:
  Py-Script:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: Python Setup
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'   

      - name: Install Dependencies
        run: | 
          pip install --upgrade pip
          pip install -r requirements/main.txt
    
      - name: flake8 test
        run: flake8 app/main.py

      - name: Execute Code
        env:
          AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
        run: python3 app/main.py
