name: Ouputs
on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.version.outputs.version}}
    steps:
      - name: Build Status
        id: status
        run: echo "status=Build Completed" >> $GITHUB_OUTPUT

      - name: Build Version
        id: version
        run: echo "version=1.0.0" >> $GITHUB_OUTPUT

      - name: Print Build Status
        run: echo ${{steps.status.outputs.status}}

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Version
        run: echo ${{needs.Build.outputs.version}}
        
        
